//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeMonitor) DeepCopyInto(out *RealtimeMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeMonitor.
func (in *RealtimeMonitor) DeepCopy() *RealtimeMonitor {
	if in == nil {
		return nil
	}
	out := new(RealtimeMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealtimeMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeMonitorList) DeepCopyInto(out *RealtimeMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RealtimeMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeMonitorList.
func (in *RealtimeMonitorList) DeepCopy() *RealtimeMonitorList {
	if in == nil {
		return nil
	}
	out := new(RealtimeMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealtimeMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeMonitorObservation) DeepCopyInto(out *RealtimeMonitorObservation) {
	*out = *in
	if in.Sensors != nil {
		in, out := &in.Sensors, &out.Sensors
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Sinks.DeepCopyInto(&out.Sinks)
	in.Variables.DeepCopyInto(&out.Variables)
	if in.SinksOptions != nil {
		in, out := &in.SinksOptions, &out.SinksOptions
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeMonitorObservation.
func (in *RealtimeMonitorObservation) DeepCopy() *RealtimeMonitorObservation {
	if in == nil {
		return nil
	}
	out := new(RealtimeMonitorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeMonitorParameters) DeepCopyInto(out *RealtimeMonitorParameters) {
	*out = *in
	if in.Sensors != nil {
		in, out := &in.Sensors, &out.Sensors
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Sinks.DeepCopyInto(&out.Sinks)
	in.Variables.DeepCopyInto(&out.Variables)
	if in.SinksOptions != nil {
		in, out := &in.SinksOptions, &out.SinksOptions
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeMonitorParameters.
func (in *RealtimeMonitorParameters) DeepCopy() *RealtimeMonitorParameters {
	if in == nil {
		return nil
	}
	out := new(RealtimeMonitorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeMonitorSpec) DeepCopyInto(out *RealtimeMonitorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeMonitorSpec.
func (in *RealtimeMonitorSpec) DeepCopy() *RealtimeMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(RealtimeMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeMonitorStatus) DeepCopyInto(out *RealtimeMonitorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeMonitorStatus.
func (in *RealtimeMonitorStatus) DeepCopy() *RealtimeMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(RealtimeMonitorStatus)
	in.DeepCopyInto(out)
	return out
}
