apiVersion: komodor.komodor.crossplane.io/v1alpha1
kind: RealtimeMonitor
metadata:
  name: example-monitor
  annotations:
    crossplane.io/external-name: ""
spec:
  forProvider:
    name: "Example Monitor"
    description: "An example monitor created by the Komodor provider"
    query: "kubernetes.container.cpu.usage.total"
    threshold: 80
    operator: ">"
    duration: "5m"
    severity: "warning"
  providerConfigRef:
    name: komodor-provider-config 