apiVersion: komodor.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: komodor-provider-config
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: komodor-api-secret
      key: api-key