apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-komodor
  labels:
    app: crossplane-komodor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-komodor
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system 