apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-komodor
  namespace: crossplane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crossplane-komodor
  template:
    metadata:
      labels:
        app: crossplane-komodor
    spec:
      containers:
      - name: provider
        image: danielyaba/crossplane-komodor:v1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace