apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-komodor
rules:
- apiGroups: ["komodor.komodor.crossplane.io"]
  resources: ["realtimemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["komodor.komodor.crossplane.io"]
  resources: ["realtimemonitors/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["komodor.crossplane.io"]
  resources: ["providerconfigs", "providerconfigusages"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-komodor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-komodor
subjects:
- kind: ServiceAccount
  name: default
  namespace: crossplane-system 